[package]
name = "slac"
version = "0.3.0"
authors = ["Dennis Prediger <dennis.prediger@gmail.com>"]
edition = "2021"
rust-version = "1.70.0"
description = "The \"Simple Logic & Arithmetic Compiler\" (SLAC) transforms a single expression into an a abstract syntax tree."
categories = ["compilers", "parsing"]
license = "Apache-2.0"
repository = "https://github.com/DennisPrediger/SLAC"
readme = "README.md"


[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json"]

[dependencies]
serde = { version = "1.0.178", optional = true, features = ["derive"] }
serde_json = { version = "1.0.104", optional = true }

[dev-dependencies]
minify = "1.3.0"
